### ISSUE TITLE
paper summary recipes

### ISSUE THREAD

**Issue by omarsar** [dair-ai/nlp_paper_summaries#11]
Hi all, 

I have this idea to potentially use the paper summaries here to help out students. I notice a lot of courses online and in universities recommend papers for students but this can be intimidating for some and even discouraging. What if we create "recipes" for students where we recommend them a journey on what paper summaries to look at first before jumping into the actual corresponding papers. Paper summaries are more approachable/friendly and can help guide students better before they jump into paper reading. This could be a nice addition as we keep expanding the list. Thoughts?

**Comment by vrdn-23** [comment]
This is a splendid idea! I personally know a lot of people who would benefit from this a lot. Question is, where do we start? Where do we select the first level of the recipe from?

**Comment by omarsar** [comment]
We can use the year as a starter to come up with the order although I wouldn't pay much attention to that. But I was thinking along the lines of improvements since a lot of papers build on top of each other as is the case for instance with Transformers models which are constantly being improved. For instance, if someones want to learn about Transformers, we suggest the Attention paper and then recommend other reads that improved the Transformer. Similarly, if it was specifically about a particular task, then we group those separately. In other words, one paper can appear in multiple recipes. There is no limit or constraint here. If we maintain them in separate .md files under a `recipes` folder it would be easy to add, modify, remove, etc.

**Comment by vrdn-23** [comment]
Yep. That sounds good! Maybe we can start off by making a recipe for every paper we've included here and see where that leads us. The challenge would be to identify the summaries of the lower-level papers as they might be more harder (or easier) to find.

**Comment by omarsar** [comment]
We are thinking of providing paper summary recipes for topics like LSTM, RNN, Transformer, etc.
