### ISSUE TITLE
Migrate all TL;DRs from previous NLP Newsletters

### ISSUE THREAD

**Issue by omarsar** [dair-ai/nlp_paper_summaries#15]
Source: https://medium.com/dair-ai

**Comment by vrdn-23** [comment]
Let me know if you need any help with this @omarsar

**Comment by omarsar** [comment]
@JavaiMaster The idea was to use the short brief explanations that I included in the previous NLP Newsletters and migrate them as TL;DRs to the corresponding folder in this repo. Note that we are only looking at NLP works. 

Find the English newsletters here: https://github.com/dair-ai/nlp_newsletter
