### ISSUE TITLE
Recipe for Transformers

### ISSUE THREAD

**Issue by omarsar** [dair-ai/nlp_paper_summaries#19]
A great summary of improvements in Transformers. It could be used to extract a great recipe around this topic. 

https://lilianweng.github.io/lil-log/2020/04/07/the-transformer-family.html

**Comment by vrdn-23** [comment]
Aah yes. This is really neat! I'll (hopefully) have a recipe that we can build up on by the end of this week hopefully.

**Comment by vrdn-23** [comment]
> Aah yes. This is really neat! I'll (hopefully) have a recipe that we can build up on by the end of this week hopefully.

So this unfortunately did not pan out. I would still need some time to compile the resources together. Would anyone want to give it a go in the meantime or is it fine if I stick with it? I think I can get something concrete by the end of this month.

**Comment by omarsar** [comment]
@JavaiMaster sounds good to me. No rush! I think the more time you take to prepare it the better I am sure it will come out. :)

**Comment by vrdn-23** [comment]
https://github.com/graykode/nlp-roadmap
Leaving this here as a reference. @omarsar do you think this is something we can build upon as a recipe template? Probably encourage users to add their own tidbits ?

**Comment by omarsar** [comment]
@vrdn-23 This will be great to build upon. I agree!
