### ISSUE TITLE
Add paper summary to privacy

### ISSUE THREAD

**Issue by omarsar** [dair-ai/nlp_paper_summaries#28]
http://www.cleverhans.io/2020/04/06/stealing-bert.html

**Comment by omarsar** [comment]
Could maybe go into ethics and NLP folder or we can create a new category named "Privacy and NLP"

**Comment by e-tornike** [comment]
Maybe it could be its own category? Would make finding the repository easier.

**Comment by omarsar** [comment]
@e-tony I agree with you Tony. Let's do that.

**Comment by e-tornike** [comment]
The summary is up for review right? I'm currently reading the associated paper. Can have a look at the summary later.

**Comment by e-tornike** [comment]
Done.
